/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_final;

import java.awt.Dimension;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andeson
 */
public class Ventana2A2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2A2
     */
    public class Imagen extends javax.swing.JPanel {

        public Imagen() {
        this.setSize(100, 100); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics

            public void paint(Graphics grafico) {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/aprobacion.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
            }
    }
    
    public class Imagen2 extends javax.swing.JPanel {

        public Imagen2() {
        this.setSize(100, 100); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics

            public void paint(Graphics grafico) {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/negacion.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
            }
    }
    public Ventana2A2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tit = new javax.swing.JLabel();
        lbl_itn = new javax.swing.JLabel();
        lbl_qasp = new javax.swing.JLabel();
        tf_qasp = new javax.swing.JTextField();
        lbl_sl = new javax.swing.JLabel();
        tf_sl = new javax.swing.JTextField();
        lbl_sm = new javax.swing.JLabel();
        tf_sm = new javax.swing.JTextField();
        lbl_poslat = new javax.swing.JLabel();
        tf_poslat = new javax.swing.JTextField();
        lbl_latdia = new javax.swing.JLabel();
        tf_latdia = new javax.swing.JTextField();
        tf_tm = new javax.swing.JTextField();
        lbl_tm = new javax.swing.JLabel();
        lbl_hld = new javax.swing.JLabel();
        tf_hld = new javax.swing.JTextField();
        lbl_ipreal = new javax.swing.JLabel();
        tf_ipreal = new javax.swing.JTextField();
        lbl_tposlat = new javax.swing.JLabel();
        tf_tposlat = new javax.swing.JTextField();
        lbl_poslatdia = new javax.swing.JLabel();
        tf_poslatdia = new javax.swing.JTextField();
        lbl_pr = new javax.swing.JLabel();
        tf_pr = new javax.swing.JTextField();
        btn_cal = new javax.swing.JButton();
        btn_lim = new javax.swing.JButton();
        btn_atr = new javax.swing.JButton();
        btn_ini = new javax.swing.JButton();
        lbl_lb = new javax.swing.JLabel();
        tf_lb = new javax.swing.JTextField();
        lbl_fr = new javax.swing.JLabel();
        tf_fr = new javax.swing.JTextField();
        panelImg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tit.setText("RIEGO POR ASPERSION");

        lbl_itn.setText("Introducir los datos:");

        lbl_qasp.setText("Qasp (m3/h)");

        lbl_sl.setText("Sl (m)");

        lbl_sm.setText("Sm (m)");

        lbl_poslat.setText("#Poslat ");

        lbl_latdia.setText("#Latdia");

        lbl_tm.setText("Tm (h)");

        lbl_hld.setText("Hld (h)");

        lbl_ipreal.setText("Ipreal (mm/h) =");

        lbl_tposlat.setText("Tposlatcorr (h) =");

        lbl_poslatdia.setText("Poslatdia (#) =");

        lbl_pr.setText("Pr (dia) =");

        btn_cal.setText("Calcular");
        btn_cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calActionPerformed(evt);
            }
        });

        btn_lim.setText("Limpiar");
        btn_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limActionPerformed(evt);
            }
        });

        btn_atr.setText("Atras");
        btn_atr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrActionPerformed(evt);
            }
        });

        btn_ini.setText("Inico");
        btn_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniActionPerformed(evt);
            }
        });

        lbl_lb.setText("Lb (mm) =");

        lbl_fr.setText("Fr (dia) =");

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lbl_tit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cal)
                                .addGap(18, 18, 18)
                                .addComponent(btn_lim))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_ipreal)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_ipreal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_lb)
                                        .addComponent(lbl_tposlat)
                                        .addComponent(lbl_poslatdia)
                                        .addComponent(lbl_fr)
                                        .addComponent(lbl_pr))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tf_lb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_poslatdia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_tposlat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_pr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_itn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_qasp)
                                    .addComponent(lbl_sl)
                                    .addComponent(lbl_sm)
                                    .addComponent(lbl_poslat)
                                    .addComponent(lbl_latdia)
                                    .addComponent(lbl_tm)
                                    .addComponent(lbl_hld))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_tm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                    .addComponent(tf_latdia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_poslat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_sm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_sl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_hld)
                                    .addComponent(tf_qasp, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_atr)
                                .addGap(37, 37, 37)
                                .addComponent(btn_ini)
                                .addGap(128, 128, 128))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tit)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_itn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_qasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_qasp))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_poslat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_poslat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_latdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_latdia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_hld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_hld)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cal)
                            .addComponent(btn_lim))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_lb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_lb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ipreal)
                            .addComponent(tf_ipreal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tposlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tposlat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_poslatdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_poslatdia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_fr)
                            .addComponent(tf_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pr)
                            .addComponent(tf_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atr)
                    .addComponent(btn_ini))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calActionPerformed
        // TODO add your handling code here:
        double num1d=0, num2d=0,num3d=0,num4d=0,num5d=0,num6d=0,num7d=0,num8d,num9d,ipreal,tposlat,tposlatcorr,poslatdia,pr;
        DecimalFormat fd=new DecimalFormat("0.00");
        String ress1,ress2,ress3,ress4;
        String num1=tf_qasp.getText();
        String num2=tf_sl.getText();
        String num3=tf_sm.getText();
        String num4=tf_poslat.getText();
        String num5=tf_latdia.getText();
        String num6=tf_tm.getText();
        String num7=tf_hld.getText();
        String num8=tf_lb.getText();
        String num9=tf_fr.getText();
        
        if(num1.isEmpty()||num2.isEmpty()||num3.isEmpty()||num4.isEmpty()||num5.isEmpty()||num6.isEmpty()||num7.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No se puede dejar campos vacios");
        }
        else
        {
            num1d=Double.parseDouble(num1);
            num2d=Double.parseDouble(num2);
            num3d=Double.parseDouble(num3);
            num4d=Double.parseDouble(num4);
            num5d=Double.parseDouble(num5);
            num6d=Double.parseDouble(num6);
            num7d=Double.parseDouble(num7);
        }
        
        num8d=Double.parseDouble(tf_lb.getText());
        num9d=Double.parseDouble(tf_fr.getText());                
        ipreal=((num1d)/(num2d*num3d))*1000;
        tposlat=(num8d)/ipreal;
        tposlatcorr=tposlat+num6d;
        poslatdia=(num7d/tposlatcorr)*num5d;
        poslatdia=Math.floor(poslatdia);
        pr=(num4d)/(poslatdia);
        ress1=String.valueOf(fd.format(ipreal));
        ress2=String.valueOf(fd.format(tposlatcorr));
        ress3=String.valueOf(fd.format(poslatdia));
        ress4=String.valueOf(fd.format(pr));
        tf_ipreal.setText(ress1);
        tf_tposlat.setText(ress2);
        tf_poslatdia.setText(ress3);
        tf_pr.setText(ress4);
        
        tf_ipreal.setText(ress1.replace(',', '.'));
        tf_tposlat.setText(ress2.replace(',', '.'));
        tf_poslatdia.setText(ress3.replace(',', '.'));
        tf_pr.setText(ress4.replace(',', '.'));
              
        if (num9d>=pr) 
        {
            Imagen Imagen = new Imagen();
            panelImg.add(Imagen);
            panelImg.repaint();
        } 
        else 
        {
            Imagen2 Imagen2 = new Imagen2();
            panelImg.add(Imagen2);
            panelImg.repaint();
        }
    }//GEN-LAST:event_btn_calActionPerformed

    private void btn_atrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrActionPerformed
        // TODO add your handling code here:
        Ventana2A1 V2A1=new Ventana2A1();
        V2A1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_atrActionPerformed

    private void btn_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniActionPerformed
        // TODO add your handling code here:
        Ventana1 V1=new Ventana1();
        V1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_iniActionPerformed

    private void btn_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limActionPerformed
        // TODO add your handling code here:
        tf_qasp.setText("");
        tf_sl.setText("");
        tf_sm.setText("");
        tf_poslat.setText("");
        tf_latdia.setText("");
        tf_tm.setText("");
        tf_hld.setText("");
        tf_ipreal.setText("");
        tf_tposlat.setText("");
        tf_poslatdia.setText("");
        tf_pr.setText("");
    }//GEN-LAST:event_btn_limActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2A2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atr;
    private javax.swing.JButton btn_cal;
    private javax.swing.JButton btn_ini;
    private javax.swing.JButton btn_lim;
    private javax.swing.JLabel lbl_fr;
    private javax.swing.JLabel lbl_hld;
    private javax.swing.JLabel lbl_ipreal;
    private javax.swing.JLabel lbl_itn;
    private javax.swing.JLabel lbl_latdia;
    private javax.swing.JLabel lbl_lb;
    private javax.swing.JLabel lbl_poslat;
    private javax.swing.JLabel lbl_poslatdia;
    private javax.swing.JLabel lbl_pr;
    private javax.swing.JLabel lbl_qasp;
    private javax.swing.JLabel lbl_sl;
    private javax.swing.JLabel lbl_sm;
    private javax.swing.JLabel lbl_tit;
    private javax.swing.JLabel lbl_tm;
    private javax.swing.JLabel lbl_tposlat;
    private javax.swing.JPanel panelImg;
    public static javax.swing.JTextField tf_fr;
    private javax.swing.JTextField tf_hld;
    private javax.swing.JTextField tf_ipreal;
    private javax.swing.JTextField tf_latdia;
    public static javax.swing.JTextField tf_lb;
    private javax.swing.JTextField tf_poslat;
    private javax.swing.JTextField tf_poslatdia;
    private javax.swing.JTextField tf_pr;
    private javax.swing.JTextField tf_qasp;
    private javax.swing.JTextField tf_sl;
    private javax.swing.JTextField tf_sm;
    private javax.swing.JTextField tf_tm;
    private javax.swing.JTextField tf_tposlat;
    // End of variables declaration//GEN-END:variables
}
