/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_final;

import java.awt.Dimension;
import java.awt.Graphics;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author andeson
 */
public class Ventana2B1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2B1
     */
    public class Imagen extends javax.swing.JPanel {

        public Imagen() {
        this.setSize(100, 100); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics

            public void paint(Graphics grafico) {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/aprobacion.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
            }
    }
    
    public class Imagen2 extends javax.swing.JPanel {

        public Imagen2() {
        this.setSize(100, 100); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics

            public void paint(Graphics grafico) {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/negacion.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
            }
    }
    
    public Ventana2B1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tit = new javax.swing.JLabel();
        lbl_fr = new javax.swing.JLabel();
        tf_fr = new javax.swing.JTextField();
        lbl_etc = new javax.swing.JLabel();
        tf_etc = new javax.swing.JTextField();
        lbl_eff = new javax.swing.JLabel();
        tf_eff = new javax.swing.JTextField();
        lbl_ip = new javax.swing.JLabel();
        tf_ip = new javax.swing.JTextField();
        lbl_hld = new javax.swing.JLabel();
        tf_hld = new javax.swing.JTextField();
        lbl_tm = new javax.swing.JLabel();
        tf_tm = new javax.swing.JTextField();
        lbl_pr = new javax.swing.JLabel();
        tf_pr = new javax.swing.JTextField();
        btn_cal = new javax.swing.JButton();
        btn_lim = new javax.swing.JButton();
        btn_ini = new javax.swing.JButton();
        lbl_itn = new javax.swing.JLabel();
        tf_ttlm = new javax.swing.JTextField();
        lbl_ttlm = new javax.swing.JLabel();
        panelImg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tit.setText("RIEGO POR GOTEO O MICROASPERSION");

        lbl_fr.setText("Fr (dia)");

        tf_fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_frActionPerformed(evt);
            }
        });

        lbl_etc.setText("ETc (mm/dia)");

        lbl_eff.setText("Eff (%)");

        lbl_ip.setText("Ip (mm/dia)");

        lbl_hld.setText("Hld (h)");

        lbl_tm.setText("Tm (h) =");

        lbl_pr.setText("Pr (dia) =");

        btn_cal.setText("Calcular");
        btn_cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calActionPerformed(evt);
            }
        });

        btn_lim.setText("Limpiar");
        btn_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limActionPerformed(evt);
            }
        });

        btn_ini.setText("Inico");
        btn_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniActionPerformed(evt);
            }
        });

        lbl_itn.setText("Introducir los datos:");

        lbl_ttlm.setText("Total mod (#)");

        javax.swing.GroupLayout panelImgLayout = new javax.swing.GroupLayout(panelImg);
        panelImg.setLayout(panelImgLayout);
        panelImgLayout.setHorizontalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImgLayout.setVerticalGroup(
            panelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lbl_tit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_itn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ttlm)
                                    .addComponent(lbl_hld, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_eff, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_etc)
                                        .addComponent(lbl_ip))
                                    .addComponent(lbl_fr, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_etc, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(tf_eff, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_ip, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_hld, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_ttlm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_fr))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_cal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_lim))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_pr)
                                            .addComponent(lbl_tm))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_pr)
                                            .addComponent(tf_tm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btn_ini)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tit)
                .addGap(18, 18, 18)
                .addComponent(lbl_itn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_etc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_etc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_eff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_eff))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ip))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_hld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_hld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ttlm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ttlm)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cal)
                            .addComponent(btn_lim))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tm))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_pr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_ini)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calActionPerformed
        // TODO add your handling code here:
        double num1d=0, num2d=0,num3d=0,num4d=0,num5d=0,num6d=0,lara,lb,tm,nmd,pr;
        DecimalFormat fd=new DecimalFormat("0.00");
        String ress1,ress2;
        String num1=tf_fr.getText();
        String num2=tf_etc.getText();
        String num3=tf_eff.getText();
        String num4=tf_ip.getText();
        String num5=tf_hld.getText();
        String num6=tf_ttlm.getText();
        
        if(num1.isEmpty()||num2.isEmpty()||num3.isEmpty()||num4.isEmpty()||num5.isEmpty()||num6.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No se puede dejar campos vacios");
        }
        else
        {
            num1d=Double.parseDouble(num1);
            num2d=Double.parseDouble(num2);
            num3d=Double.parseDouble(num3);
            num4d=Double.parseDouble(num4);
            num5d=Double.parseDouble(num5);
            num6d=Double.parseDouble(num6);
        }
        
        lara=num1d*num2d;
        lb=lara/(num3d/100);
        tm=lb/num4d;
        nmd=num5d/tm;
        nmd=Math.floor(nmd);
        pr=num6d/nmd;
        
        ress1=String.valueOf(fd.format(tm));
        ress2=String.valueOf(fd.format(pr));
        tf_tm.setText(ress1);
        tf_pr.setText(ress2);
        
        tf_tm.setText(ress1.replace(',', '.'));
        tf_pr.setText(ress2.replace(',', '.'));
        
        if (num1d>=pr) 
        {
            Imagen Imagen = new Imagen();
            panelImg.add(Imagen);
            panelImg.repaint();
        } 
        else 
        {
            Imagen2 Imagen2 = new Imagen2();
            panelImg.add(Imagen2);
            panelImg.repaint();
        }
    }//GEN-LAST:event_btn_calActionPerformed

    private void btn_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniActionPerformed
        // TODO add your handling code here:
        Ventana1 V1=new Ventana1();
        V1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_iniActionPerformed

    private void tf_frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_frActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_frActionPerformed

    private void btn_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limActionPerformed
        // TODO add your handling code here:
        tf_fr.setText("");
        tf_etc.setText("");
        tf_eff.setText("");
        tf_ip.setText("");
        tf_hld.setText("");
        tf_ttlm.setText("");
        tf_tm.setText("");
        tf_pr.setText("");
    }//GEN-LAST:event_btn_limActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2B1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2B1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cal;
    private javax.swing.JButton btn_ini;
    private javax.swing.JButton btn_lim;
    private javax.swing.JLabel lbl_eff;
    private javax.swing.JLabel lbl_etc;
    private javax.swing.JLabel lbl_fr;
    private javax.swing.JLabel lbl_hld;
    private javax.swing.JLabel lbl_ip;
    private javax.swing.JLabel lbl_itn;
    private javax.swing.JLabel lbl_pr;
    private javax.swing.JLabel lbl_tit;
    private javax.swing.JLabel lbl_tm;
    private javax.swing.JLabel lbl_ttlm;
    private javax.swing.JPanel panelImg;
    private javax.swing.JTextField tf_eff;
    private javax.swing.JTextField tf_etc;
    private javax.swing.JTextField tf_fr;
    private javax.swing.JTextField tf_hld;
    private javax.swing.JTextField tf_ip;
    private javax.swing.JTextField tf_pr;
    private javax.swing.JTextField tf_tm;
    private javax.swing.JTextField tf_ttlm;
    // End of variables declaration//GEN-END:variables
}
