/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_final;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author andeson
 */
public class Ventana2A1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2A1
     */
    public Ventana2A1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_etc = new javax.swing.JLabel();
        tf_etc = new javax.swing.JTextField();
        tf_f = new javax.swing.JTextField();
        lbl_f = new javax.swing.JLabel();
        lbl_pe = new javax.swing.JLabel();
        tf_pe = new javax.swing.JTextField();
        tf_da = new javax.swing.JTextField();
        lbl_da = new javax.swing.JLabel();
        lbl_wpmp = new javax.swing.JLabel();
        tf_wpmp = new javax.swing.JTextField();
        tf_wcc = new javax.swing.JTextField();
        lbl_wcc = new javax.swing.JLabel();
        lbl_int = new javax.swing.JLabel();
        lbl_tit = new javax.swing.JLabel();
        lbl_lara = new javax.swing.JLabel();
        tf_lara = new javax.swing.JTextField();
        tf_lb = new javax.swing.JTextField();
        lbl_lb = new javax.swing.JLabel();
        lbl_fr = new javax.swing.JLabel();
        tf_fr = new javax.swing.JTextField();
        lbl_des = new javax.swing.JLabel();
        rbt_si = new javax.swing.JRadioButton();
        rbt_no = new javax.swing.JRadioButton();
        btn_cal = new javax.swing.JButton();
        btn_lim = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        btn_atr = new javax.swing.JButton();
        lbl_eff = new javax.swing.JLabel();
        tf_eff = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_etc.setText("ETc (mm/dia)");

        lbl_f.setText("F (%)");

        lbl_pe.setText("Pe (mm)");

        lbl_da.setText("Da (gr/cc)");

        lbl_wpmp.setText("Wpmp (%)");

        lbl_wcc.setText("Wcc (%)");

        lbl_int.setText("Introducir los datos:");

        lbl_tit.setText("RIEGO POR ASPERSION");

        lbl_lara.setText("LARA (mm) =");

        lbl_lb.setText("Lb (mm) =");

        lbl_fr.setText("Fr (dia) =");

        lbl_des.setText("Desea aproximar Fr al valor mas cercano y recalcular");

        buttonGroup1.add(rbt_si);
        rbt_si.setText("Si");
        rbt_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_siActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbt_no);
        rbt_no.setText("No");

        btn_cal.setText("Calcular");
        btn_cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calActionPerformed(evt);
            }
        });

        btn_lim.setText("Limpiar");
        btn_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limActionPerformed(evt);
            }
        });

        btn_sig.setText("Siguiente");
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });

        btn_atr.setText("Atras");
        btn_atr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrActionPerformed(evt);
            }
        });

        lbl_eff.setText("Eff (%)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_int)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_wpmp)
                                    .addComponent(lbl_da)
                                    .addComponent(lbl_pe)
                                    .addComponent(lbl_wcc))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_pe, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(tf_wpmp)
                                    .addComponent(tf_da)
                                    .addComponent(tf_wcc)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_f)
                                    .addComponent(lbl_etc)
                                    .addComponent(lbl_eff))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_etc)
                                    .addComponent(tf_f)
                                    .addComponent(tf_eff))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_lara)
                                            .addComponent(lbl_lb)
                                            .addComponent(lbl_fr))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_lara, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                            .addComponent(tf_lb)
                                            .addComponent(tf_fr))
                                        .addGap(0, 114, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_cal)
                                        .addGap(38, 38, 38)
                                        .addComponent(btn_lim)
                                        .addGap(34, 34, 34))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbt_si)
                                    .addComponent(rbt_no)
                                    .addComponent(lbl_des))
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_sig)
                        .addGap(40, 40, 40)
                        .addComponent(btn_atr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbl_tit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_tit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_int)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_wcc)
                            .addComponent(tf_wcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_wpmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_wpmp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_da))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_pe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_pe))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_f))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_etc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_etc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_eff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_eff)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_cal)
                                    .addComponent(btn_lim))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_lara)
                                    .addComponent(tf_lara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_lb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lb))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_des)
                            .addGap(48, 48, 48))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbt_si)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rbt_no))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sig)
                    .addComponent(btn_atr))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_siActionPerformed

    private void btn_calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calActionPerformed
        // TODO add your handling code here:
        double num1d=0, num2d=0,num3d=0,num4d=0,num5d=0,num6d=0,num7d=0,lara,lb,fr;
        DecimalFormat fd=new DecimalFormat("0.00");
        String ress1,ress2,ress3,ress4,ress5;
        String num1=tf_wcc.getText();
        String num2=tf_wpmp.getText();
        String num3=tf_da.getText();
        String num4=tf_pe.getText();
        String num5=tf_f.getText();
        String num6=tf_etc.getText();
        String num7=tf_eff.getText();
        
        if(num1.isEmpty()||num2.isEmpty()||num3.isEmpty()||num4.isEmpty()||num5.isEmpty()||num6.isEmpty()||num7.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"No se puede dejar campos vacios");
        }
        else
        {
            num1d=Double.parseDouble(num1);
            num2d=Double.parseDouble(num2);
            num3d=Double.parseDouble(num3);
            num4d=Double.parseDouble(num4);
            num5d=Double.parseDouble(num5);
            num6d=Double.parseDouble(num6);
            num7d=Double.parseDouble(num7);
        }
        
        if(rbt_si.isSelected()==false&&rbt_no.isSelected()==false)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar si desea aproximar la frecuencia de riego");
        }
        else
        {
            if(rbt_si.isSelected()==true)
            {
                lara=((num1d/100)-(num2d/100))*num3d*num4d*(num5d/100);
                lb=lara/(num7d/100);
                fr=lara/num6d;
                fr=Math.round(fr);
                lara=fr*num6d;
                lb=lara/(num7d/100);
                ress1=String.valueOf(fd.format(lara));
                ress2=String.valueOf(fd.format(lb));
                ress3=String.valueOf(fd.format(fr));
                tf_lara.setText(ress1);
                tf_lb.setText(ress2);
                tf_fr.setText(ress3);
                
                tf_lara.setText(ress1.replace(',', '.'));
                tf_lb.setText(ress2.replace(',', '.'));
                tf_fr.setText(ress3.replace(',', '.'));
            }
            
            if(rbt_no.isSelected()==true)
            {
                lara=((num1d/100)-(num2d/100))*num3d*num4d*(num5d/100);
                lb=lara/(num7d/100);
                fr=lara/num6d;
                ress1=String.valueOf(fd.format(lara));
                ress2=String.valueOf(fd.format(lb));
                ress3=String.valueOf(fd.format(fr));
                tf_lara.setText(ress1);
                tf_lb.setText(ress2);
                tf_fr.setText(ress3);
                
                tf_lara.setText(ress1.replace(',', '.'));
                tf_lb.setText(ress2.replace(',', '.'));
                tf_fr.setText(ress3.replace(',', '.'));
            }
        }
    }//GEN-LAST:event_btn_calActionPerformed

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        // TODO add your handling code here:        
        Ventana2A2 V2A2=new Ventana2A2();
        V2A2.setVisible(true);        
        V2A2.tf_lb.setText(tf_lb.getText());
        V2A2.tf_fr.setText(tf_fr.getText());
        dispose();
    }//GEN-LAST:event_btn_sigActionPerformed

    private void btn_atrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrActionPerformed
        // TODO add your handling code here:
        Ventana1 V1=new Ventana1();
        V1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_atrActionPerformed

    private void btn_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limActionPerformed
        // TODO add your handling code here:        
        tf_wcc.setText("");
        tf_wpmp.setText("");
        tf_da.setText("");
        tf_pe.setText("");
        tf_f.setText("");
        tf_etc.setText("");
        tf_eff.setText("");
        tf_lara.setText("");
        tf_lb.setText("");
        tf_fr.setText("");
    }//GEN-LAST:event_btn_limActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2A1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2A1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2A1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2A1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2A1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atr;
    private javax.swing.JButton btn_cal;
    private javax.swing.JButton btn_lim;
    private javax.swing.JButton btn_sig;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbl_da;
    private javax.swing.JLabel lbl_des;
    private javax.swing.JLabel lbl_eff;
    private javax.swing.JLabel lbl_etc;
    private javax.swing.JLabel lbl_f;
    private javax.swing.JLabel lbl_fr;
    private javax.swing.JLabel lbl_int;
    private javax.swing.JLabel lbl_lara;
    private javax.swing.JLabel lbl_lb;
    private javax.swing.JLabel lbl_pe;
    private javax.swing.JLabel lbl_tit;
    private javax.swing.JLabel lbl_wcc;
    private javax.swing.JLabel lbl_wpmp;
    private javax.swing.JRadioButton rbt_no;
    private javax.swing.JRadioButton rbt_si;
    private javax.swing.JTextField tf_da;
    private javax.swing.JTextField tf_eff;
    private javax.swing.JTextField tf_etc;
    private javax.swing.JTextField tf_f;
    private javax.swing.JTextField tf_fr;
    private javax.swing.JTextField tf_lara;
    private javax.swing.JTextField tf_lb;
    private javax.swing.JTextField tf_pe;
    private javax.swing.JTextField tf_wcc;
    private javax.swing.JTextField tf_wpmp;
    // End of variables declaration//GEN-END:variables
}
